# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# we need to
	# build the sequence
	# find the evens
	# sum those numbers
# all at the same time ^_^

def fibbi_sum(max_num, div):
	sum = 0
	fibbi_dig_1 = 1
	fibbi_dig_2 = 1
	place_holder = 0
	while fibbi_dig_2 < max_num:
		if fibbi_dig_2 % 2 == 0:
			sum += fibbi_dig_2
		place_holder = fibbi_dig_2
		fibbi_dig_2 = fibbi_dig_1 + fibbi_dig_2
		fibbi_dig_1 = place_holder
	return sum

print fibbi_sum(20, 2)
print fibbi_sum(4000000, 2)

# this works